# Generated by Django 4.0.1 on 2022-03-27 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teeamo', '0011_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime_of_payment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
